%YAML 1.1
---
# yaml-language-server: $schema=./schema.default.json

logging:
  format: '%(asctime)s %(levelname)s:%(name)s:%(message)s'
  datefmt: '%Y-%m-%d %H:%M:%S'

# REMIND-specific settings
remind_coupling:
  # Enforce REMIND capacities via constraint in solve_network.py
  installed_capacities:
    generators: true
    links: true
    stores: true
  # Hydrogen settings
  hydrogen_storage:
    hydrogen_underground_storage_locations:
      - onshore
      - nearshore
  # Battery settings
  battery_storage:
    e_min_pu: 0.15
  sector_coupling:
    electrolysis:
      # Add load for electrolytic hydrogen
      enable: true
      # Minimum partial load
      p_min_pu: 0.1
      # Ramping limit
      ramp_limit: NaN
    EV_pass:
      # Add load for EV passenger
      enable: false
      annual_consumption: 3
      charge_rate: 0.011
      share_charger: 0.8
      dsm: false
      battery_size: 0.06
      dsm_availability: 0.5
    EV_freight:
      # Add load for EV freight (currently not used)
      enable: false
      annual_consumption: 40
      charge_rate: 0.15
      share_charger: 0.1
      dsm: false
      battery_size: 0.3
      dsm_availability: 0.5
    heatpump:
      # Add load for heat pumps
      enable: false
      avg_power: 0.002
      hours_used: 2000
      dsm: false
      tank_delT: 40
      tank_size: 200
      tank_share: 0.9
      dsm_availability: 0.5
    resistive:
      # Add load for resistive heating
      enable: false
      avg_power: 0.006
      hours_used: 500
      dsm: false
      tank_delT: 40
      tank_size: 200
      tank_share: 0.1
      dsm_availability: 0.5
  export_to_REMIND:
    z_cutoff: 3

run:
  disable_progressbar: true
  # Share resources across REMIND scenarios
  shared_resources:
    policy: true

scenario:
  clusters:
    - 4
  opts:
    - 3H
  year:
    - 2025
    - 2030
    - 2035
    - 2040
    - 2045
    - 2050
    - 2055
    - 2060
    - 2070
    - 2080
    - 2090
    - 2100
    - 2110
    - 2130
    - 2150
  # TODO: Check where this is relevant
  planning_horizons:
    - 2025
    - 2030
    - 2035
    - 2040
    - 2045
    - 2050
    - 2055
    - 2060
    - 2070
    - 2080
    - 2090
    - 2100
    - 2110
    - 2130
    - 2150

# TODO: Adjust based on regPy32 set from REMIND
countries:
  - DE

electricity:
  extendable_carriers:
    # TODO: Review solar-hsat, biomass
    Generator:
      - solar
      - onwind
      - offwind-ac
      - offwind-dc
      - OCGT
      - nuclear
      - oil
      - CCGT
      - coal
      - lignite
  # Powerplants are filtered in adjust_powerplants_REMIND
  powerplants_filter: false
  # Add powerplants at all locations
  everywhere_powerplants:
    - OCGT
    - nuclear
    - oil
    - CCGT
    - coal
    - lignite
    - biomass
  # TODO: What about waste and geothermal?
  conventional_carriers:
    - OCGT
    - nuclear
    - oil
    - CCGT
    - coal
    - lignite
    - biomass
  # TODO: What about solar-hsat?
  renewable_carriers:
    - solar
    - onwind
    - offwind-ac
    - offwind-dc
    - hydro
  # Don't estimate renewable capacities for now
  estimate_renewable_capacities:
    enable: false

# Adjust potentials to match REMIND
renewable:
  offwind-ac:
    capacity_per_sqkm: 5.6
  offwind-dc:
    capacity_per_sqkm: 5.6
  solar:
    capacity_per_sqkm: 21.5

sector:
  district_heating:
    supply_temperature_approximation:
      # Ensure consistency with REMIND across all years
      relative_annual_temperature_reduction: 0

solving:
  options:
    load_shedding: 1
    # Inject constraints for minimum capacities
    custom_extra_functionality: ../scripts/remind_extra_constraints.py
  gurobi_hpc_tunnel:
    use_tunnel: false
    tunnel_port: 26998
    login_node: '02'
    timeout_s: 15
  solver_options:
    gurobi-default:
      threads: 8
  mem_mb: 30000
  memory_logging_frequency: 30
  runtime: 6h
